USE ROLE SECURITYADMIN;



--Role Creation
CREATE ROLE DV0_ROLE_IRIS_ASK_IRIS_USER;
CREATE ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;
CREATE ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;



--Grant Role to SYSADMIN
GRANT ROLE DV0_ROLE_IRIS_ASK_IRIS_USER TO SYSADMIN;
GRANT ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER TO SYSADMIN;
GRANT ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL TO SYSADMIN;



USE ROLE SYSADMIN; 
USE DATABASE AZIRIS_SERVDWSD;



--Schema Creation
CREATE SCHEMA DV0_IRIS_ASKIRIS_STAGE WITH MANAGED ACCESS DEFAULT_DDL_COLLATION = 'en-ci';
CREATE SCHEMA DV0_IRIS_ASKIRIS_DB WITH MANAGED ACCESS DEFAULT_DDL_COLLATION = 'en-ci';
CREATE SCHEMA DV0_IRIS_ASKIRIS_VIEWS WITH MANAGED ACCESS DEFAULT_DDL_COLLATION = 'en-ci';



--Grant Usage for Warehouse
GRANT USAGE ON WAREHOUSE WH_IRIS_SERV_SMALL TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT USAGE ON WAREHOUSE WH_IRIS_SERV_SMALL TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;
GRANT USAGE ON WAREHOUSE WH_IRIS_SERV_SMALL TO ROLE DV0_ROLE_IRIS_ASK_IRIS_USER;
GRANT USAGE ON WAREHOUSE WH_IRIS_SERV_XSMALL TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT USAGE ON WAREHOUSE WH_IRIS_SERV_XSMALL TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;
GRANT USAGE ON WAREHOUSE WH_IRIS_SERV_XSMALL TO ROLE DV0_ROLE_IRIS_ASK_IRIS_USER;



--Grant Usage for Database
GRANT USAGE ON DATABASE AZIRIS_SERVDWSD TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT USAGE ON DATABASE AZIRIS_SERVDWSD TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;
GRANT USAGE ON DATABASE AZIRIS_SERVDWSD TO ROLE DV0_ROLE_IRIS_ASK_IRIS_USER;



--Grant Usage on STAGE
GRANT USAGE ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL; 
GRANT USAGE ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--Grant Usage om dB
GRANT USAGE ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL; 
GRANT USAGE ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--Grant Usage om Views
GRANT USAGE ON SCHEMA DV0_IRIS_ASKIRIS_VIEWS TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL; 
GRANT USAGE ON SCHEMA DV0_IRIS_ASKIRIS_VIEWS TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;
GRANT USAGE ON SCHEMA DV0_IRIS_ASKIRIS_VIEWS TO ROLE DV0_ROLE_IRIS_ASK_IRIS_USER;



--Grant Usage on External Stage
GRANT USAGE ON FUTURE STAGES IN SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT USAGE ON FUTURE STAGES IN SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--Grant Usage on File Formats
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



---Grant Create Role on Stage and FILE
GRANT CREATE STAGE ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT CREATE STAGE ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;
GRANT CREATE FILE FORMAT ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT CREATE FILE FORMAT ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--Table Access for Dev and ETL
GRANT CREATE TABLE ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT CREATE TABLE ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT CREATE TABLE ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--Sequence Access for Dev and ETL
GRANT CREATE SEQUENCE ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT CREATE SEQUENCE ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--Functiom Access for Dev and ETL
GRANT CREATE FUNCTION ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT CREATE FUNCTION ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--Procedure Access for Dev and ETL
GRANT CREATE PROCEDURE ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT CREATE PROCEDURE ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--Tasks Access for Dev and ETL
GRANT CREATE TASK ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT CREATE TASK ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--Pipes Access for Dev and ETL
GRANT CREATE PIPE ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT CREATE PIPE ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--Stage Access for Dev and ETL
GRANT CREATE STAGE ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT CREATE STAGE ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--File Format Access for Dev and ETL
GRANT CREATE FILE FORMAT ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT CREATE FILE FORMAT ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--Stream Access for Dev and ETL
GRANT CREATE STREAM ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT CREATE STREAM ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--View Access for Dev and ETL
GRANT CREATE VIEW ON SCHEMA DV0_IRIS_ASKIRIS_VIEWS TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT CREATE VIEW ON SCHEMA DV0_IRIS_ASKIRIS_VIEWS TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



--Grants tables and views access
GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA DV0_IRIS_ASKIRIS_STAGE TO DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA DV0_IRIS_ASKIRIS_STAGE TO DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA DV0_IRIS_ASKIRIS_DB TO DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA DV0_IRIS_ASKIRIS_DB TO DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;



GRANT SELECT ON FUTURE VIEWS  IN SCHEMA  DV0_IRIS_ASKIRIS_VIEWS TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA  DV0_IRIS_ASKIRIS_VIEWS TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA  DV0_IRIS_ASKIRIS_VIEWS TO ROLE DV0_ROLE_IRIS_ASK_IRIS_USER;



USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DV0_ROLE_IRIS_ASK_IRIS_ETL;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DV0_ROLE_IRIS_ASK_IRIS_DEVELOPER;






-- Object Access Admin
GRANT ALL PRIVILEGES ON SCHEMA DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_SERV_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_SERV_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA DV0_IRIS_ASKIRIS_VIEWS TO ROLE DV0_ROLE_IRIS_SERV_ADMIN;



---Objects Access ADMIN
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA  DV0_IRIS_ASKIRIS_STAGE TO ROLE DV0_ROLE_IRIS_SERV_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA  DV0_IRIS_ASKIRIS_DB TO ROLE DV0_ROLE_IRIS_SERV_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE VIEWS  IN SCHEMA  DV0_IRIS_ASKIRIS_VIEWS TO ROLE DV0_ROLE_IRIS_SERV_ADMIN;